[connections.snowflake]
account = "TYTFNSY-TLC18698"
user = "KVEERASA1"
password = "2023AcuraRDXAspec"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true